version: '3.1'
services:
  rest:
    image: sdbrother/rest
    container_name: rest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.1.6:5432/db1
      SPRING.DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres