spring:
  sql:
    init:
      platform: postgres
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: validate
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.6:5432/db1
    username: postgres
    password: postgres